### ISSUE TITLE
Naming overlap: alantech/highlightjs-alan and highlightjs/highlightjs-alan

### ISSUE THREAD

**Issue by joshgoebel** [highlightjs/highlightjs-alan-if#6]
https://github.com/alantech/highlightjs-alan
https://github.com/highlightjs/highlightjs-alan

_Are neither of these published on NPM?_  If there are truly different languages could we come up with a different name for the final package to remove any potential confusion users might have?

**Comment by tajmone** [comment]
Yes, they are different languages altogether.

I should then rename the repository to `highlightjs-alan-if` and the language to `Alan-IF`, this would resolve the name conflict.

**Comment by joshgoebel** [comment]
Sounds about right to me (just looking at the names we already have in the list).

**Comment by joshgoebel** [comment]
Can you rename the repo then?  If not let me know and I can rename it - then we just need a PR to update the supported languages list with the new URL.
